# Generated by Django 3.1.5 on 2021-01-29 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0003_auto_20210128_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_added',
            field=models.ManyToManyField(related_name='added_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
