# Generated by Django 3.1.5 on 2021-01-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_auto_20210126_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planitem',
            old_name='quantity',
            new_name='grams',
        ),
    ]
