# Generated by Django 3.1.5 on 2021-01-26 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20210126_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.recipe'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.product'),
        ),
    ]
