# Generated by Django 3.1.5 on 2021-01-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_auto_20210126_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='planitem',
            name='recipe',
        ),
        migrations.AddField(
            model_name='planitem',
            name='recipe',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='planner.Recipe'),
        ),
    ]
