# Generated by Django 3.1.5 on 2021-01-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20210126_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planitem',
            name='recipe',
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField(blank=True, default=0, null=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.product')),
                ('recipe', models.ManyToManyField(blank=True, default=None, null=True, to='planner.Recipe')),
            ],
        ),
    ]
