# Generated by Django 3.1.5 on 2021-01-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_auto_20210126_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeitem',
            name='recipe',
        ),
        migrations.AddField(
            model_name='plan',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, to='planner.Recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='items',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='planner.RecipeItem'),
        ),
    ]
