# Generated by Django 3.1.5 on 2021-01-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20210127_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='type',
            field=models.CharField(choices=[('3d', '3-day plan'), ('7d', '7-day plan')], max_length=12),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='day',
            field=models.CharField(choices=[('1', 'Day 1'), ('2', 'Day 2'), ('3', 'Day 3'), ('4', 'Day 4'), ('5', 'Day 5'), ('6', 'Day 6'), ('7', 'Day 7')], max_length=10),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='time',
            field=models.CharField(blank=True, choices=[('br', 'Breakfast'), ('ln', 'Lunch'), ('dn', 'Dinner'), ('sn', 'Snack')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
