# Generated by Django 3.1.5 on 2021-01-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_auto_20210128_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='day',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
